### ISSUE TITLE
WinError6: Invalid Handle

### ISSUE THREAD

**Issue by niemtec** [niemtec/media-file-classifier#5]
Throws WinError6 when reading some files:

```
Traceback (most recent call last):
  File "C:/Users/X/Documents/GitHub/media-file-classifier/file-classifier.py", line 39, in <module>
    duration = GetDuration(file)

  File "C:/Users/X/Documents/GitHub/media-file-classifier/file-classifier.py", line 23, in GetDuration
    clip = VideoFileClip(path_to_file)

  File "C:\Program Files\Python36\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 81, in __init__
    fps_source=fps_source)
  
File "C:\Program Files\Python36\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 68, in __init__
    self.initialize()
 
 File "C:\Program Files\Python36\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 103, in initialize
    self.proc = sp.Popen(cmd, **popen_params)
 
 File "C:\Program Files\Python36\lib\subprocess.py", line 594, in __init__
    _cleanup()
 
 File "C:\Program Files\Python36\lib\subprocess.py", line 205, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
 
 File "C:\Program Files\Python36\lib\subprocess.py", line 1027, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] The handle is invalid
```

**Comment by niemtec** [comment]
Fixed.
